# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aggregator}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakob Borg"]
  s.date = %q{2010-01-13}
  s.description = %q{Aggregator is a Ruby library that does aggregation (data reduction) on old data in an RTG database.}
  s.email = %q{jakob@nym.se}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "aggregator.gemspec",
     "lib/aggregator.rb",
     "lib/extensions.rb",
     "test/aggregator_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/calmh/RTG-Aggregator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{RTG Data Aggregation library}
  s.test_files = [
    "test/aggregator_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mysql>, [">= 0"])
    else
      s.add_dependency(%q<mysql>, [">= 0"])
    end
  else
    s.add_dependency(%q<mysql>, [">= 0"])
  end
end

